# Gauss' method: inverse of a matrix

The following function reproduces the Gauss' method for computing the inverse of a matrix $A$ according to the expression $\quad L_n L_{n-1}\ldots L_1 A = \mathbb I\quad\Rightarrow\quad L_n L_{n-1}\ldots L_1 \mathbb I = A^{-1}$

In [14]:
def inverseMatrix(matrix):
    '''
    Function that computes the inverse of a matrix
    Args:
        matrix - original matrix
    Returns:
        inverseA - inverse of the orginal matrix
    '''
    
    import numpy as np
    
    # idA: Original matrix that we want to transform into the identity
    idA = np.copy(np.array(matrix))
    # inverseA: Identity, which is going to be transformed into the inverse of the original matrix
    inverseA = np.identity(len(idA))
    
    for j in range(len(idA)):

        # L: matrix encoding an elementary row operation for every step in the loop    
        L = np.identity(len(idA))
        L[j, j] /= idA[j, j]
        
        idA = np.dot(L, idA)
        inverseA = np.dot(L, inverseA)
        
        for i in range(len(idA)):
            if i != j:
                
                L = np.identity(len(idA))
                L[i, j] = -idA[i, j]
                
                idA = np.dot(L, idA)
                inverseA = np.dot(L, inverseA)
    
    return inverseA.tolist()
    

We can check the function with the following example:
$$A=\begin{pmatrix}2&1&1\\1&1&1\\2&3&2\end{pmatrix}\qquad\qquad A^{-1}=\begin{pmatrix}1&-1&0\\0&-2&1\\-1&4&-1\end{pmatrix}$$

In [16]:
import numpy as np

A = np.array([[2, 1, 1], [1, 1, 1], [2, 3, 2]])
print(A)

[[2 1 1]
 [1 1 1]
 [2 3 2]]


In [15]:
# NumPy function to compute the inverse of A
print(np.linalg.inv(A))

print('=')

# My custom function to compute the inverse of A
print(np.array(inverseMatrix(A)))

[[ 1. -1.  0.]
 [ 0. -2.  1.]
 [-1.  4. -1.]]
=
[[ 1. -1.  0.]
 [ 0. -2.  1.]
 [-1.  4. -1.]]
